package whoislib

// This map is used to determine the whois server for a given TLD.
var WhoisSupportedTlds = map[string]string{
	"cn": "whois.cnnic.cn",
	"中国": "cwhois.cnnic.cn",
	"中國": "cwhois.cnnic.cn",
	"hk": "whois.hkirc.hk",
	"tw": "whois.twnic.net.tw",
	"so": "whois.nic.so",
	"sg": "whois.sgnic.sg",
	"mo": "whois.monic.mo",
	"ru": "whois.tcinet.ru",
	"su": "whois.tcinet.ru",
	"au": "whois.auda.org.au",
	"us": "whois.nic.us",
	"co": "whois.nic.co",
	"kr": "whois.kr",
	"im": "whois.nic.im",
	"ir": "whois.nic.ir",
	"in": "whois.registry.in",
	"tr": "whois.trabis.gov.tr",
	"io": "whois.nic.io",
	"me": "whois.nic.me",
	"jp": "whois.jprs.jp",
	"by": "whois.cctld.by",
	"eu": "whois.eu",
	"pl": "whois.dns.pl",
	"it": "whois.nic.it",
	"mx": "whois.mx",
	"ro": "whois.rotld.ro",
	"se": "whois.iis.se",
	"dk": "whois.punktum.dk",
	"be": "whois.dns.be",
	"at": "whois.nic.at",
	"lu": "whois.dns.lu",
	"qa": "whois.registry.qa",
	"ie": "whois.weare.ie",
	"af": "whois.nic.af",
	"bn": "whois.bnnic.bn",
	"bh": "whois.nic.bh",
	"sa": "whois.nic.net.sa",
	"ee": "whois.tld.ee",
	"sk": "whois.sk-nic.sk",
	"kn": "whois.nic.kn",
	"lt": "whois.domreg.lt",
	"lv": "whois.nic.lv",
	"om": "whois.registry.om",
	"sc": "whois.nic.sc",
	"ag": "whois.nic.ag",
	"cl": "whois.nic.cl",
	"mk": "whois.marnet.mk",
	"gg": "whois.gg",
	"ng": "whois.nic.net.ng",
	"do": "whois.nic.do",
	"am": "whois.amnic.net",
	"rs": "whois.rnids.rs",
	"bg": "whois.register.bg",
	"hr": "whois.dns.hr",
	"mn": "whois.nic.mn",
	"ae": "whois.aeda.net.ae",
	"th": "whois.thnic.co.th",
	"hu": "whois.nic.hu",
	"md": "whois.nic.md",
	"kz": "whois.nic.kz",
	"pe": "kero.yachay.pe",
	"my": "whois.mynic.my",
	"ws": "whois.website.ws",
	"fi": "whois.fi",
	"il": "whois.isoc.org.il",
	"za": "whois.registry.net.za",
	"pt": "whois.dns.pt",
	"de": "whois.denic.de",
	"nz": "whois.irs.net.nz",
}

var WhoisTldOptions = map[string]string{
	"de": "-T dn,ace",
}
